events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    keepalive_timeout 65;

    # HTTP -> HTTPS 리디렉션
    server {
        listen 80;
        server_name marketten.shop;
        return 301 https://$host$request_uri;
    }

    # HTTPS 메인 서버
    server {
        listen 443 ssl;
        server_name marketten.shop;

        ssl_certificate     /etc/letsencrypt/live/marketten.shop/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/marketten.shop/privkey.pem;
        ssl_protocols       TLSv1.2 TLSv1.3;
        ssl_ciphers         HIGH:!aNULL:!MD5;

        root /usr/share/nginx/html;
        index index.html;

        # React Router 대응
        location / {
            try_files $uri $uri/ /index.html;
        }

        # 백엔드 프록시
        location /api/ {
            proxy_pass http://backend:8080/api/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
        }

        # FastAPI 프록시
        location /fastapi/ {
            proxy_pass http://module:8000/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
        }

        # 이미지 요청
	           # 이미지 요청
        location ^~ /images/ {
            proxy_pass http://backend:8080/images/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
	
	location /oauth2/authorization/ { # OAuth2 시작 경로
            proxy_pass http://backend:8080/oauth2/authorization/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
        }

        location /login/oauth2/code/ { # OAuth2 콜백 경로
            proxy_pass http://backend:8080/login/oauth2/code/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
        }

        # 정적 리소스 캐싱
        location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|ttf|svg|mp4)$ {
            expires 1y;
            add_header Cache-Control "public, immutable";
            try_files $uri $uri/ /index.html;
        }
    }
}
